import type { TokenPayload } from './jwt.js';

export type SystemRoleName =
  | 'platform_admin'
  | 'tenant_owner'
  | 'tenant_admin'
  | 'project_manager'
  | 'lead_assessor'
  | 'assessor'
  | 'quality_manager'
  | 'risk_manager'
  | 'viewer';

export const SYSTEM_ROLE_PERMISSIONS: Record<SystemRoleName, string[]> = {
  platform_admin: [
    'tenant:read',
    'tenant:update',
    'tenant:delete',
    'user:impersonate',
    'audit_log:read',
    'audit_log:export',
    'admin:read',
    'admin:write',
    'dashboard:read',
  ],
  tenant_owner: [
    'tenant:read',
    'tenant:update',
    'tenant:delete',
    'tenant:manage_members',
    'tenant:manage_billing',
    'role:read',
    'role:create',
    'role:update',
    'role:delete',
    'user:read',
    'user:create',
    'user:update',
    'user:delete',
    'api_key:*',
    'webhook:*',
    'integration:*',
    'assessment:read',
    'assessment:create',
    'assessment:update',
    'assessment:delete',
    'assessment:complete',
    'assessment:export',
    'assessment.response:read',
    'assessment.response:write',
    'assessment.response:review',
    'assessment.template:read',
    'assessment.template:create',
    'assessment.template:update',
    'assessment.template:delete',
    'risk:read',
    'risk:create',
    'risk:update',
    'risk:delete',
    'risk:accept',
    'risk:export',
    'risk.register:read',
    'risk.register:create',
    'risk.register:update',
    'risk.register:delete',
    'risk.treatment:read',
    'risk.treatment:create',
    'risk.treatment:update',
    'risk.treatment:delete',
    'finding:read',
    'finding:create',
    'finding:update',
    'finding:delete',
    'finding:transition',
    'finding:assign',
    'finding:export',
    'evidence:read',
    'evidence:upload',
    'evidence:update',
    'evidence:delete',
    'evidence:download',
    'evidence:verify',
    'zone:read',
    'zone:create',
    'zone:update',
    'zone:delete',
    'conduit:read',
    'conduit:create',
    'conduit:update',
    'conduit:delete',
    'purdue:read',
    'purdue:create',
    'purdue:update',
    'purdue:delete',
    'csms:read',
    'csms:create',
    'csms:update',
    'csms:delete',
    'csms:approve_policy',
    'remediation:read',
    'remediation:create',
    'remediation:update',
    'remediation:delete',
    'remediation:verify',
    'remediation:assign',
    'asset:read',
    'asset:create',
    'asset:update',
    'asset:delete',
    'asset:import',
    'asset:export',
    'report:read',
    'report:generate',
    'report:download',
    'report:delete',
    'audit_log:read',
    'audit_log:export',
    'admin:read',
    'admin:write',
    'dashboard:read',
    'csms:write',
    'report:write',
  ],
  tenant_admin: [
    'tenant:read',
    'tenant:update',
    'tenant:manage_members',
    'role:read',
    'role:create',
    'role:update',
    'user:read',
    'user:create',
    'user:update',
    'user:delete',
    'api_key:*',
    'webhook:*',
    'integration:*',
    'assessment:read',
    'assessment:create',
    'assessment:update',
    'assessment:delete',
    'assessment:complete',
    'assessment:export',
    'assessment.response:read',
    'assessment.response:write',
    'assessment.response:review',
    'assessment.template:read',
    'assessment.template:create',
    'assessment.template:update',
    'risk:read',
    'risk:create',
    'risk:update',
    'risk:delete',
    'risk:accept',
    'risk:export',
    'risk.register:read',
    'risk.register:create',
    'risk.register:update',
    'risk.register:delete',
    'risk.treatment:read',
    'risk.treatment:create',
    'risk.treatment:update',
    'finding:read',
    'finding:create',
    'finding:update',
    'finding:delete',
    'finding:transition',
    'finding:assign',
    'finding:export',
    'evidence:read',
    'evidence:upload',
    'evidence:update',
    'evidence:delete',
    'evidence:download',
    'evidence:verify',
    'zone:read',
    'zone:create',
    'zone:update',
    'zone:delete',
    'conduit:read',
    'conduit:create',
    'conduit:update',
    'conduit:delete',
    'purdue:read',
    'purdue:create',
    'purdue:update',
    'purdue:delete',
    'csms:read',
    'csms:create',
    'csms:update',
    'csms:delete',
    'csms:approve_policy',
    'remediation:read',
    'remediation:create',
    'remediation:update',
    'remediation:delete',
    'remediation:verify',
    'remediation:assign',
    'asset:read',
    'asset:create',
    'asset:update',
    'asset:delete',
    'asset:import',
    'asset:export',
    'report:read',
    'report:generate',
    'report:download',
    'report:delete',
    'audit_log:read',
    'audit_log:export',
    'admin:read',
    'admin:write',
    'dashboard:read',
    'csms:write',
    'report:write',
  ],
  project_manager: [
    'assessment:read',
    'assessment:create',
    'assessment:update',
    'assessment:delete',
    'assessment:complete',
    'assessment:export',
    'assessment.template:read',
    'assessment.template:create',
    'assessment.template:update',
    'risk:read',
    'risk:create',
    'risk:update',
    'risk:delete',
    'risk:accept',
    'risk:export',
    'risk.register:read',
    'risk.register:create',
    'risk.register:update',
    'risk.register:delete',
    'risk.treatment:read',
    'risk.treatment:create',
    'risk.treatment:update',
    'finding:read',
    'finding:create',
    'finding:update',
    'finding:delete',
    'finding:transition',
    'finding:assign',
    'finding:export',
    'remediation:read',
    'remediation:create',
    'remediation:update',
    'remediation:delete',
    'remediation:verify',
    'remediation:assign',
    'report:read',
    'report:generate',
    'report:download',
    'report:delete',
    'asset:read',
    'asset:create',
    'asset:update',
    'asset:delete',
    'asset:import',
    'asset:export',
    'evidence:read',
    'evidence:upload',
    'evidence:update',
    'evidence:download',
    'evidence:verify',
    'zone:read',
    'zone:create',
    'zone:update',
    'conduit:read',
    'conduit:create',
    'conduit:update',
    'purdue:read',
    'purdue:create',
    'purdue:update',
    'assessment.response:read',
    'assessment.response:write',
    'assessment.response:review',
    'dashboard:read',
    'csms:write',
    'report:write',
  ],
  lead_assessor: [
    'assessment:read',
    'assessment:create',
    'assessment:update',
    'assessment:export',
    'assessment.response:read',
    'assessment.response:write',
    'assessment.response:review',
    'assessment.template:read',
    'finding:read',
    'finding:create',
    'finding:update',
    'finding:transition',
    'finding:assign',
    'evidence:read',
    'evidence:upload',
    'evidence:update',
    'evidence:download',
    'evidence:verify',
    'risk:read',
    'risk:create',
    'risk:update',
    'zone:read',
    'zone:create',
    'zone:update',
    'conduit:read',
    'conduit:create',
    'conduit:update',
    'purdue:read',
    'purdue:create',
    'purdue:update',
    'asset:read',
    'asset:create',
    'asset:update',
    'report:read',
    'report:generate',
    'report:download',
    'csms:read',
    'remediation:read',
    'dashboard:read',
  ],
  assessor: [
    'assessment:read',
    'assessment.response:read',
    'assessment.response:write',
    'finding:read',
    'finding:create',
    'finding:update',
    'evidence:read',
    'evidence:upload',
    'evidence:download',
    'zone:read',
    'conduit:read',
    'purdue:read',
    'asset:read',
    'risk:read',
    'csms:read',
    'remediation:read',
    'report:read',
    'dashboard:read',
  ],
  quality_manager: [
    'assessment:read',
    'assessment:complete',
    'assessment:export',
    'assessment.response:read',
    'assessment.response:review',
    'finding:read',
    'finding:update',
    'finding:transition',
    'risk:read',
    'risk:accept',
    'evidence:read',
    'evidence:verify',
    'remediation:read',
    'remediation:verify',
    'csms:read',
    'csms:approve_policy',
    'report:read',
    'report:generate',
    'report:download',
    'audit_log:read',
    'audit_log:export',
    'dashboard:read',
    'admin:read',
    'csms:write',
    'report:write',
  ],
  risk_manager: [
    'risk:read',
    'risk:create',
    'risk:update',
    'risk:delete',
    'risk:accept',
    'risk:export',
    'risk.register:read',
    'risk.register:create',
    'risk.register:update',
    'risk.treatment:read',
    'risk.treatment:create',
    'risk.treatment:update',
    'risk.treatment:delete',
    'finding:read',
    'assessment:read',
    'zone:read',
    'asset:read',
    'report:read',
    'report:generate',
    'report:download',
    'dashboard:read',
    'report:write',
  ],
  viewer: [
    'assessment:read',
    'finding:read',
    'risk:read',
    'zone:read',
    'conduit:read',
    'purdue:read',
    'csms:read',
    'remediation:read',
    'asset:read',
    'evidence:read',
    'report:read',
    'report:download',
    'dashboard:read',
  ],
};

export function resolvePermissions(roles: string[]): string[] {
  const permissionSet = new Set<string>();

  for (const role of roles) {
    const permissions = SYSTEM_ROLE_PERMISSIONS[role as SystemRoleName];
    if (permissions) {
      for (const perm of permissions) {
        permissionSet.add(perm);
      }
    }
  }

  return Array.from(permissionSet);
}

export function hasPermission(payload: TokenPayload, requiredPermission: string): boolean {
  const permissions = payload.permissions ?? resolvePermissions(payload.roles ?? []);

  if (permissions.includes(`${requiredPermission.split(':')[0]}:*`)) {
    return true;
  }

  return permissions.includes(requiredPermission);
}

export function hasAnyPermission(payload: TokenPayload, requiredPermissions: string[]): boolean {
  return requiredPermissions.some((p) => hasPermission(payload, p));
}

export function hasAllPermissions(payload: TokenPayload, requiredPermissions: string[]): boolean {
  return requiredPermissions.every((p) => hasPermission(payload, p));
}
